<script setup>
import { computed } from 'vue'
import { usePregnancyStore } from '../../stores/pregnancy.js'
import { useAmbient } from '../../composables/useAmbient.js'
import { SOUNDSCAPES } from '../../services/ambientAudio.js'

const props = defineProps({
  // 'full' for Settings, 'compact' for the single button on the Today screen.
  variant: { type: String, default: 'full' }
})

const store = usePregnancyStore()
// Destructured so the template auto-unwraps the refs rather than reading
// `.value` on every binding.
const {
  supported: audioSupported,
  playing,
  busy,
  toggle: toggleAmbient,
  change,
  setVolume: applyVolume
} = useAmbient()

const settings = computed(() => store.state.settings)
const volume = computed(() => settings.value.ambientVolume ?? 0.5)
const chosen = computed(() => settings.value.ambientSound || 'womb')

async function toggle() {
  await toggleAmbient(chosen.value, volume.value)
}

async function choose(id) {
  await store.updateSettings({ ambientSound: id })
  await change(id, volume.value)
}

async function setVolume(event) {
  const value = Number(event.target.value) / 100
  await store.updateSettings({ ambientVolume: value })
  applyVolume(value)
}
</script>

<template>
  <button
    v-if="props.variant === 'compact'"
    class="bc-tap px-4 py-2.5 rounded-xl text-sm border transition hover:opacity-70 flex items-center gap-2 disabled:opacity-50"
    :style="{
      borderColor: playing ? 'var(--bc-accent)' : 'var(--bc-hairline)',
      color: playing ? 'var(--bc-accent)' : 'inherit'
    }"
    :disabled="!audioSupported || busy"
    :aria-pressed="playing"
    :aria-label="playing ? 'Stop ambient sound' : 'Play ambient sound'"
    @click="toggle"
  >
    <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M11 5L6 9H3v6h3l5 4V5zM15.5 8.5a5 5 0 010 7M18.5 5.5a9 9 0 010 13"
      />
    </svg>
    {{ playing ? 'Sound on' : 'Ambient sound' }}
  </button>

  <section v-else class="bc-card p-5">
    <h2 class="font-medium mb-1">Ambient sound</h2>
    <p class="text-sm bc-muted mb-4">
      Something quiet to speak over. Generated by the app, so it works offline and never loops
      audibly.
    </p>

    <p v-if="!audioSupported" class="text-sm bc-muted">This browser cannot play generated audio.</p>

    <template v-else>
      <div class="space-y-2 mb-4">
        <button
          v-for="sound in SOUNDSCAPES"
          :key="sound.id"
          class="bc-tap w-full text-left px-4 py-3 rounded-xl border transition"
          :style="{
            borderColor: chosen === sound.id ? 'var(--bc-accent)' : 'var(--bc-hairline)',
            backgroundColor: chosen === sound.id ? 'var(--bc-surface)' : 'transparent'
          }"
          :aria-pressed="chosen === sound.id"
          @click="choose(sound.id)"
        >
          <span class="block text-sm font-medium">{{ sound.label }}</span>
          <span class="block text-xs bc-muted mt-0.5">{{ sound.description }}</span>
        </button>
      </div>

      <label class="flex items-center gap-4 mb-4">
        <span class="text-sm shrink-0">Volume</span>
        <input
          type="range"
          min="0"
          max="100"
          step="1"
          class="w-full"
          :value="Math.round(volume * 100)"
          aria-label="Ambient volume"
          @input="setVolume"
        />
      </label>

      <button
        class="bc-tap px-4 py-2.5 rounded-xl text-sm font-medium text-white transition disabled:opacity-50"
        :style="{ backgroundColor: 'var(--bc-accent)' }"
        :disabled="busy"
        @click="toggle"
      >
        {{ playing ? 'Stop' : 'Play' }}
      </button>
    </template>
  </section>
</template>
